name: Mi Flujo de Trabajo

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: chequeo de codigo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        #if: github.ref == 'refs/heads/master' # Solo master
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_net_web:latest

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: despliegue tarea
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with: 
          task-definition: taskdefinition.json
          cluster: CloudJavier
          wait-for-service-stability: true
