name: Mi Flujo de Trabajo

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: chequeo de codigo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        #if: github.ref == 'refs/heads/master' # Solo master
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
